# Interactive component

For the interactive component, I build a d3 object where the over-reporting rate can be compared across years for select variables: gender and race. In the main results sections, I avoided presenting multiple identical plots that varied only in time, except for the map plots. Instead, I aggregated all data points across years. The assumption there was that the pattern in each year would be broadly consistent with the aggregate pattern. It is possible, however, that this fails to capture interesting insight that we can unearth only by looking at changes over time. To illustrate the point, I created bar charts that change when the user chooses a different year to view. The default visualization uses data from 2008.

See for visualization of gender differences:

https://vizhub.com/mandu427/6cc35a21157e482b8f354a65ca5b6c2d?edit=files&file=index.html&line&mode=full

Note that I had two ways of visualizing this: (1) holding the y scale constant and allowing the height of bars to vary and, (2) varying the y scale depending on the maximum values of the data. My visualization does (2). The advantage of setting the maximum value of the y scale as the maximum y value in the data for each year, is that it makes it easier to focus on the *difference* between Female and Male.  Of course, an attentive audience can also take note of the changing overall levels of over-reporting, by looking at the numbers on the scale. On the other hand, had I done (1) and fixed the y scale to a set number, it would have been easier to spot the *changes* in overall levels (for both Female and Male), but it may be harder to see the changes in the difference between the two categories, especially if the difference is marginal. 

In this case, the gender plot shows that overall levels of overreporting are higher in years 2012 and 2016 compared to 2008. The gap between Female and Male increased in 2012, but returns to similar levels in 2016. In this case there isn't a clear pattern over time, and it's possible that the difference is statistically not significant. This could be an area of further analysis.

https://vizhub.com/mandu427/268ba661bb3d4f0ba82188fa0a60d689?edit=files&file=index.html&line&mode=full

The second link produces a similar plot, but for race. Again, I use the maximum y value in each year as the maximum value of the y scale, which makes it easier how the relative differences across racial groups change over time. From these visualizations it's quite easy to see that the over-reporting rate among Asians has increased relative to the share of Whites, from 2008 to 2012, and again in 2016. I don't have an a priori theory about this change, and it's important to note that it's also possible that some of the change is due to sampling, since the number of observations for Asians (e.g. 612 in year 2016) is much smaller than for Whites (9,710 in 2016). However, the change seems to be substantial, and it would be interesting to investigate the reasons behind this.

The code for the interactive visualizations were based on modificatoins of this code: https://www.d3-graph-gallery.com/graph/barplot_button_data_hard.html