# Conclusion

The main limitations of this project--related to the fact that we cannot distinguish between administrative errors and lies--were discussed at the outset. Despite this challenge, it is possible, at least for variables that I examined, to identify a few patterns that predict overreporting.

It would be interesting, time permitting, to look at additional political variables, such as margins of the elections, which party won, etc. to see if these electoral outcomes also have an effect on overreporting. The challenge here though would be that electoral outcome would be identical for all respondents within electoral administrative units (i.e. state, congressional district (CD)), and given that the same party consistently wins many states, there may not be sufficient variation in electoral outcomes at state level (although more variation would be seen at CD level) with data from only 3 years.

The main challenge I encountered writing up the results was figuring out how to communicate the "findings." In statistics, we often speak in terms of p-values and significance levels, so I found myself keep asking whether the pattern I was seeing was "clear enough" or if the differences in groups were really "noticeable." As we learned in the course, scales can really make a difference, and while it's tempting to opt for "findings," it's important to avoid presenting patterns where there is none. All of this is just to say that it's been great learning complementarity of dataviz and statistics! 