--- 
title: "Self-reported voter turnout"
author: "Jiyeon Chang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Average turnout rates in US elections hover around 50-60%, but in surveys, the figure is often closer to 70-80%. Why is that? It's possible that this gap is attributable to nonresponse bias, but survey researchers report that social desirability bias also plays a role. Social desirability bias is the tendency among survey respondents to choose an answer that they believe to be good, rather than one that reflects their true beliefs or behaviors. In the case of turnout, this means that there are people who lie about whether they voted, i.e. they say they voted even though in reality they did not. This is a tricky issue for survey researchers, as it introduces bias in the data, leading to overreporting. In this project, I look at what are some of the variables that may explain the phenomenon of overreporting.

The main dataset I use to explore this question is the Cooperative Congressional Election Study (https://cces.gov.harvard.edu/). The survey asks respondents whether they voted in the recent election. For each respondent, there is a variable indicating whether there exists a record of that person of having voted. The strategy here is to look at respondents for whom there is *no* record of voting, i.e. whom we can assume to not have voted. Once we have this subsample, we can compare the group of people that claims to have voted (record does not match what they say) vs. those who say that they did not vote (their statement matches the missing record). 

One word of caution: For those who claim to have voted, there are two possible explanations for why there might not be a corresponding voting record for them. First, it may have been an administrative error--a common reason for this is that the person moved recently, and that their voting record is not up-to-date. In this case, the missing record is not an indication that they are lying. Another possibility, however, is that the respondent is be lying. There is no definitive way to distinguish which of the missing records are due to error vs. lying. However, if we can assume that the rate of administrative error should be random across different subsamples of interests, then it *is* possible to examine which groups are more likely to over-report turnout. 

To this end, I present the findings based on the following three questions:

1. Does overreporting vary by state, and if so, is there a useful pattern there?
2. How does overreporting vary by key demographic and political traits?
3. Does having strong/large social networks increase the probability that an individual will overreport, conditional on not having voted?


